# frozen_string_literal: true

require 'cgi/escape'
require 'fileutils'
require 'time'
require_relative 'metrics_export_options'

module ArchUnit
  module Metrics
    # Self-contained metrics report rendering and export.
    module Reporting
      # Renders caller-supplied metric data as a complete offline HTML document.
      module MetricsExporter
        DEFAULT_CSS = <<~CSS
          :root { color-scheme: light dark; font-family: system-ui, sans-serif; }
          body { max-width: 960px; margin: 0 auto; padding: 2rem; }
          h1 { margin-bottom: .25rem; }
          .timestamp { color: #666; margin-top: 0; }
          table { border-collapse: collapse; margin-top: 1.5rem; width: 100%; }
          th, td { border: 1px solid #bbb; padding: .6rem .8rem; text-align: left; }
          th { background: rgba(127, 127, 127, .14); }
          tr:nth-child(even) { background: rgba(127, 127, 127, .07); }
          footer { color: #666; font-size: .85rem; margin-top: 2rem; }
        CSS

        module_function

        def export_as_html(data, options = nil)
          raise ArgumentError, 'data must be a Hash' unless data.is_a?(Hash)

          options = MetricsExportOptions.resolve(options)
          html = render(data, options).freeze
          write(options.output_path, html) if options.output_path
          html
        end

        def render(data, options)
          title = escape(options.title)
          <<~HTML
            <!DOCTYPE html>
            <html lang="en">
            #{document_head(title, options)}
            #{document_body(title, data, options)}
            </html>
          HTML
        end
        private_class_method :render

        def document_head(title, options)
          <<~HTML.chomp
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>#{title}</title>
              <style>#{safe_css(options.custom_css || DEFAULT_CSS)}</style>
            </head>
          HTML
        end
        private_class_method :document_head

        def document_body(title, data, options)
          <<~HTML.chomp
            <body>
              <main>
                <h1>#{title}</h1>
                #{timestamp(options)}
                #{metric_table(data)}
              </main>
              <footer>Generated by ArchUnitRuby</footer>
            </body>
          HTML
        end
        private_class_method :document_body

        def metric_table(data)
          <<~HTML.chomp
            <table>
              <thead><tr><th>Metric</th><th>Value</th></tr></thead>
              <tbody>#{rows(data)}</tbody>
            </table>
          HTML
        end
        private_class_method :metric_table

        def rows(data)
          return '<tr><td colspan="2">No metric data.</td></tr>' if data.empty?

          data.map do |name, value|
            "<tr><td>#{escape(name)}</td><td>#{escape(value)}</td></tr>"
          end.join
        end
        private_class_method :rows

        def timestamp(options)
          return '' unless options.include_timestamp

          value = Time.now.utc.iso8601
          %(<p class="timestamp">Generated: #{escape(value)}</p>)
        end
        private_class_method :timestamp

        def write(output_path, html)
          path = html_path(output_path)
          directory = File.dirname(path)
          FileUtils.mkdir_p(directory) unless directory == '.'
          File.binwrite(path, html.encode(Encoding::UTF_8))
          nil
        end
        private_class_method :write

        def html_path(path)
          return path if File.extname(path).casecmp?('.html')

          "#{path}.html"
        end
        private_class_method :html_path

        def escape(value)
          CGI.escapeHTML(value.to_s)
        end
        private_class_method :escape

        def safe_css(value)
          value.gsub(%r{</style}i, '<\\/style')
        end
        private_class_method :safe_css
      end
    end
  end
end
