# frozen_string_literal: true

require 'csv'
require 'json'
require 'pathname'
require 'tmpdir'

RSpec.describe ArchUnit::GraphRenderer do
  let(:snapshot) do
    ArchUnit::GraphReportSnapshot.new(
      title: 'Architecture <Main>',
      nodes: [
        ArchUnit::GraphReportNode.new(id: 'n0', label: 'app/"api".rb'),
        ArchUnit::GraphReportNode.new(id: 'n1', label: 'domain<&>.rb'),
        ArchUnit::GraphReportNode.new(id: 'n2', label: 'faraday')
      ],
      edges: [
        ArchUnit::GraphReportEdge.new(
          source: 'app/"api".rb', target: 'domain<&>.rb', count: 2,
          external: false, import_kinds: %i[autoload require]
        ),
        ArchUnit::GraphReportEdge.new(
          source: 'app/"api".rb', target: 'faraday', count: 1,
          external: true, import_kinds: [:require]
        )
      ],
      summary: ArchUnit::GraphReportSummary.new(
        node_count: 3, edge_count: 2, raw_edge_count: 3, external_edge_count: 1
      )
    )
  end

  it 'renders valid escaped DOT with counts and external styling' do
    dot = described_class.to_dot(snapshot)

    expect(dot).to start_with('digraph dependencies {')
    expect(dot).to include(
      'label="Architecture <Main>";',
      '"app/\\"api\\".rb" -> "domain<&>.rb" [label="2"',
      '"app/\\"api\\".rb" -> "faraday" [style=dashed'
    )
    expect(dot).to end_with('}')
  end

  it 'renders Mermaid with stable snapshot node IDs and safe labels' do
    mermaid = described_class.to_mermaid(snapshot)

    expect(mermaid).to include(
      'flowchart LR',
      'n0["app/&quot;api&quot;.rb"]',
      'n1["domain&lt;&amp;&gt;.rb"]',
      'n0 -->|2| n1',
      'n0 -.-> n2'
    )
  end

  it 'renders D2 with aggregation labels and external edge styling' do
    d2 = described_class.to_d2(snapshot)

    expect(d2).to include(
      '# Architecture <Main>',
      '"app/\\"api\\".rb" -> "domain<&>.rb": "2"',
      '"app/\\"api\\".rb" -> "faraday" { style.stroke-dash: 4 }'
    )
  end

  it 'renders standards-compliant CSV containing all edge evidence' do
    csv = described_class.to_csv(snapshot)
    rows = CSV.parse(csv, headers: true)

    expect(rows.headers).to eq(%w[source target count external import_kinds])
    expect(rows.length).to eq(2)
    expect(rows.first.to_h).to eq(
      'source' => 'app/"api".rb', 'target' => 'domain<&>.rb',
      'count' => '2', 'external' => 'false',
      'import_kinds' => 'autoload|require'
    )
    expect(rows[-1]['external']).to eq('true')
  end

  it 'renders the complete snapshot as parseable stable JSON' do
    json = described_class.to_json(snapshot)
    parsed = JSON.parse(json)

    expect(parsed).to include('title' => 'Architecture <Main>')
    expect(parsed.fetch('nodes').length).to eq(3)
    expect(parsed.fetch('edges').first).to include(
      'count' => 2, 'external' => false,
      'import_kinds' => %w[autoload require]
    )
    expect(parsed.fetch('summary')).to eq(
      'node_count' => 3, 'edge_count' => 2,
      'raw_edge_count' => 3, 'external_edge_count' => 1
    )
  end

  it 'renders a self-contained offline HTML report with escaped content' do
    html = described_class.to_html(snapshot)

    expect(html).to start_with('<!DOCTYPE html>')
    expect(html).to include(
      '<title>Architecture &lt;Main&gt;</title>',
      'Generated by ArchUnitRuby graph reporting',
      '<strong>3</strong>Nodes',
      'app/&quot;api&quot;.rb',
      'domain&lt;&amp;&gt;.rb',
      '<summary>Mermaid</summary>',
      '<summary>JSON snapshot</summary>'
    )
    expect(html).not_to match(%r{https?://|<script\b|\bimport\s+mermaid})
    expect(html.scan('<html').length).to eq(1)
    expect(html.scan('</html>').length).to eq(1)
  end

  it 'exports every format as UTF-8 into newly created parent directories' do
    Dir.mktmpdir('archunit-graph-exports') do |directory|
      described_class::RENDERERS.each_key do |format|
        path = Pathname.new(directory).join('nested', "report.#{format}")
        rendered = described_class.public_send("to_#{format}", snapshot)

        expect(described_class.public_send("export_as_#{format}", snapshot, path)).to be_nil
        expect(path.binread.force_encoding(Encoding::UTF_8)).to eq(rendered)
      end
    end
  end

  it 'rejects invalid snapshots, formats, and export paths' do
    expect { described_class.to_dot(Object.new) }
      .to raise_error(ArgumentError, /GraphReportSnapshot/)
    expect { described_class.render(snapshot, :svg) }
      .to raise_error(ArgumentError, /unknown graph report format/)
    expect { described_class.export(snapshot, :json, '') }
      .to raise_error(ArgumentError, /output_path/)
  end
end
