# frozen_string_literal: true

require 'tmpdir'

RSpec.describe ArchUnit::MetricsExporter do
  it 'renders a complete escaped self-contained report with a UTC timestamp' do
    allow(Time).to receive(:now).and_return(Time.utc(2026, 8, 10, 18, 30, 0))

    html = described_class.export_as_html('<script>alert(1)</script>' => '<strong>7</strong>')

    expect(html).to include(
      '<!DOCTYPE html>', '<meta charset="utf-8">',
      '&lt;script&gt;alert(1)&lt;/script&gt;', '&lt;strong&gt;7&lt;/strong&gt;',
      'Generated: 2026-08-10T18:30:00Z', 'Generated by ArchUnitRuby'
    )
    expect(html).not_to include('<script>alert(1)</script>', '<strong>7</strong>')
    expect(html).to be_frozen
  end

  it 'supports a custom title and CSS while allowing timestamps to be omitted' do
    options = ArchUnit::MetricsExportOptions.new(
      title: 'Team <Metrics>', include_timestamp: false,
      custom_css: 'body { color: red; } </style><script>bad()</script>'
    )

    html = described_class.export_as_html({ score: 2.5 }, options)

    expect(html).to include(
      '<title>Team &lt;Metrics&gt;</title>', 'body { color: red; }', '<\/style>'
    )
    expect(html).not_to include('Generated:', '</style><script>')
  end

  it 'creates nested output directories and appends the HTML extension' do
    Dir.mktmpdir do |root|
      output = Pathname.new(root).join('nested', 'quality-report')
      options = ArchUnit::MetricsExportOptions.new(
        output_path: output, include_timestamp: false
      )

      html = described_class.export_as_html({ 'Cohésion' => 0.2 }, options)
      written = output.sub_ext('.html')

      expect(written).to exist
      expect(File.binread(written).force_encoding(Encoding::UTF_8)).to eq(html)
      expect(html).to include('Cohésion')
    end
  end

  it 'renders an explicit empty state' do
    html = described_class.export_as_html(
      {}, ArchUnit::MetricsExportOptions.new(include_timestamp: false)
    )

    expect(html).to include('No metric data.')
  end

  it 'validates report data and every option' do
    expect { described_class.export_as_html([]) }.to raise_error(ArgumentError, /Hash/)
    expect { described_class.export_as_html({}, :bad) }
      .to raise_error(ArgumentError, /MetricsExportOptions/)
    expect { ArchUnit::MetricsExportOptions.new(title: '') }
      .to raise_error(ArgumentError, /title/)
    expect { ArchUnit::MetricsExportOptions.new(output_path: '') }
      .to raise_error(ArgumentError, /output_path/)
    expect { ArchUnit::MetricsExportOptions.new(include_timestamp: :yes) }
      .to raise_error(ArgumentError, /true or false/)
    expect { ArchUnit::MetricsExportOptions.new(custom_css: '') }
      .to raise_error(ArgumentError, /custom_css/)
  end
end
